/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomeScreen.java
 *
 * Created on 23/05/2012, 4:27:28 PM
 */
package groupass;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFormattedTextField;

/**
 *
 * @author z3375080
 */
public class AddExpense extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public AddExpense() {
        initComponents();
        setSysDate();
    }
    private Home returnHomeScreen;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descInput = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        payeeInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        expenseIDinput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        daySelect = new javax.swing.JComboBox();
        monthSelect = new javax.swing.JComboBox();
        yearSelect = new javax.swing.JComboBox();
        statusText = new javax.swing.JTextField();
        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        addExpenseItemButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();
        addCostCentreButton = new javax.swing.JButton();
        editCostCentreButton = new javax.swing.JButton();
        editExistingExpense = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel6.setPreferredSize(new java.awt.Dimension(45, 15));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EXPENSE", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1024, 768));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-continue-button.png"))); // NOI18N
        next.setText("Continue");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        descInput.setColumns(20);
        descInput.setRows(5);
        jScrollPane1.setViewportView(descInput);

        jLabel4.setText("Description:");

        jLabel5.setText("Date:");

        jLabel3.setText("Payee:");

        expenseIDinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseIDinputActionPerformed(evt);
            }
        });

        jLabel2.setText("Expense ID:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Add a new Expense");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-action-back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-clear-button.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        daySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        daySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySelectActionPerformed(evt);
            }
        });

        monthSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        yearSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        statusText.setEditable(false);
        statusText.setText("Ready!");
        statusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusText))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(next)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payeeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expenseIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(expenseIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payeeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(clear)
                    .addComponent(next))
                .addGap(40, 40, 40)
                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        navigationPanel.setBackground(new java.awt.Color(244, 244, 244));
        navigationPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navigationPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        navigationPanel.setPreferredSize(new java.awt.Dimension(266, 591));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-home.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addExpenseItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-log.png"))); // NOI18N
        addExpenseItemButton.setText("Log an Expense to Cost Centre");
        addExpenseItemButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseItemButtonActionPerformed(evt);
            }
        });

        addExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addExpenseButton.setText("Add an Expense");
        addExpenseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        addCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addCostCentreButton.setText("Add a Cost Centre");
        addCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostCentreButtonActionPerformed(evt);
            }
        });

        editCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editCostCentreButton.setText("Edit an Existing Cost Centre");
        editCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCostCentreButtonActionPerformed(evt);
            }
        });

        editExistingExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editExistingExpense.setText("Edit an Existing Expense");
        editExistingExpense.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editExistingExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExistingExpenseActionPerformed(evt);
            }
        });

        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-report-button.png"))); // NOI18N
        reportsButton.setText("Create Reports");
        reportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b.png"))); // NOI18N

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reportsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editExistingExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCostCentreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCostCentreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addExpenseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addExpenseItemButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(204, 204, 204))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editExistingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));
        jPanel4.setPreferredSize(new java.awt.Dimension(787, 102));

        title.setFont(new java.awt.Font("Lao UI", 1, 55)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cost Tracker Pro");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(99, 99, 99))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try {
            if (expenseIDinput.getText() != null && payeeInput.getText() != null && daySelect.getSelectedIndex() != 0 && monthSelect.getSelectedIndex() != 0 && yearSelect.getSelectedIndex() != 0) {
                Integer expenseID = new Integer(expenseIDinput.getText());
                int day = new Integer(daySelect.getSelectedItem().toString());
                int month = new Integer(monthSelect.getSelectedIndex());
                int year = new Integer(yearSelect.getSelectedItem().toString());
                GregorianCalendar date = new GregorianCalendar(year, month, day);

                String payee = payeeInput.getText();
                String desc = descInput.getText();
                Expense newExpense = new Expense(expenseID, date, payee, desc);
                setStatus("New expense created");
                newExpense.addExpense();

                AddExpenseToCC logExpense = new AddExpenseToCC();
                logExpense.setReturnExpenseScreen(this);
                this.setVisible(false);
                logExpense.setVisible(true);
                logExpense.setStatus("Expense successfully created - you can now log it against an existing cost centre");
            }
            else {
                setStatus("Please fill in all the required fields");
            }
        } catch (java.lang.NumberFormatException nfe) {
            setStatus("Invalid expense ID");
        }

    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        returnHomeScreen.setStatus("Ready!");
        this.setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_homeButtonActionPerformed

    private void addExpenseItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseItemButtonActionPerformed
        AddExpenseToCC logExpense = new AddExpenseToCC();
        this.setVisible(false);
        logExpense.setVisible(true);
    }//GEN-LAST:event_addExpenseItemButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void addCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostCentreButtonActionPerformed
        AddCostCentre addCostCentre = new AddCostCentre();
        this.setVisible(false);
        addCostCentre.setVisible(true);
    }//GEN-LAST:event_addCostCentreButtonActionPerformed

    private void editCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCostCentreButtonActionPerformed
        EditDeleteCostCentre editCostCentre = new EditDeleteCostCentre();
        this.setVisible(false);
        editCostCentre.setVisible(true);
    }//GEN-LAST:event_editCostCentreButtonActionPerformed

    private void editExistingExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExistingExpenseActionPerformed
        EditDeleteExpense editExpense = new EditDeleteExpense();
        this.setVisible(false);
        editExpense.setVisible(true);
    }//GEN-LAST:event_editExistingExpenseActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        ReportsPage createReport = new ReportsPage();
        this.setVisible(false);
        createReport.setVisible(true);
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.clearFields();
    }//GEN-LAST:event_clearActionPerformed

    private void daySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daySelectActionPerformed

    private void expenseIDinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseIDinputActionPerformed
        expenseIDinput.setBackground(Color.white);
    }//GEN-LAST:event_expenseIDinputActionPerformed

    private void statusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddExpense().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCostCentreButton;
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton addExpenseItemButton;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox daySelect;
    private javax.swing.JTextArea descInput;
    private javax.swing.JButton editCostCentreButton;
    private javax.swing.JButton editExistingExpense;
    private javax.swing.JTextField expenseIDinput;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox monthSelect;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton next;
    private javax.swing.JTextField payeeInput;
    private javax.swing.JButton reportsButton;
    private javax.swing.JTextField statusText;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox yearSelect;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the returnHomeScreen
     */
    public Home getReturnHomeScreen() {
        return returnHomeScreen;
    }

    /**
     * @param returnHomeScreen the returnHomeScreen to set
     */
    public void setReturnHomeScreen(Home returnHomeScreen) {
        this.returnHomeScreen = returnHomeScreen;
    }

    public void clearFields() {
        expenseIDinput.setText("");        
        descInput.setText("");
        payeeInput.setText("");
        setSysDate();
    }
    
    public void setStatus(String s) {
        statusText.setText(s);
    }
    
    public void setSysDate() {
        GregorianCalendar sysDate = new GregorianCalendar();
        daySelect.setSelectedIndex(sysDate.get(Calendar.DAY_OF_MONTH));
        monthSelect.setSelectedIndex(sysDate.get(Calendar.MONTH) + 1);
        yearSelect.setSelectedIndex(sysDate.get(Calendar.YEAR) - 2004);
    }
}
