/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomeScreen.java
 *
 * Created on 23/05/2012, 4:27:28 PM
 */
package groupass;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author z3375080
 */
public class EditDeleteExpense extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public EditDeleteExpense() {
        initComponents();
    }
    private Home returnHomeScreen;
    private Expense expenseResult;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descInput = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        payeeInput = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        amountInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        expenseIDfind = new javax.swing.JButton();
        expenseIDinput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        expenseID = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        yearSelect = new javax.swing.JComboBox();
        monthSelect = new javax.swing.JComboBox();
        daySelect = new javax.swing.JComboBox();
        statusText = new javax.swing.JTextField();
        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        addExpenseItemButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();
        addCostCentreButton = new javax.swing.JButton();
        editCostCentreButton = new javax.swing.JButton();
        editExistingExpense = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EXPENSE", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N

        jLabel4.setText("Description:");

        jLabel3.setText("Payee:");

        descInput.setColumns(20);
        descInput.setRows(5);
        jScrollPane1.setViewportView(descInput);

        jLabel5.setText("Date:");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-action-back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-clear-button.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        amountInput.setEditable(false);

        jLabel6.setText("Running Total:");

        jLabel2.setText("Expense ID:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Edit an Expense");

        jLabel8.setText("Enter the Expense you would like to update or delete");

        expenseIDfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-search-database.png"))); // NOI18N
        expenseIDfind.setText("Find");
        expenseIDfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseIDfindActionPerformed(evt);
            }
        });

        jLabel7.setText("Expense ID:");

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-delete-button.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        expenseID.setText("-");

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-update-db-icon.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        yearSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        monthSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        daySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        daySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySelectActionPerformed(evt);
            }
        });

        statusText.setEditable(false);
        statusText.setText("Ready!");
        statusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusText)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(clear)
                                .addGap(56, 56, 56)
                                .addComponent(delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(expenseID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(expenseIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(expenseIDfind, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(amountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(7, 7, 7)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(payeeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseIDfind)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(expenseID))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payeeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(clear)
                    .addComponent(delete)
                    .addComponent(update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        navigationPanel.setBackground(new java.awt.Color(244, 244, 244));
        navigationPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navigationPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        navigationPanel.setPreferredSize(new java.awt.Dimension(266, 591));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-home.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addExpenseItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-log.png"))); // NOI18N
        addExpenseItemButton.setText("Log an Expense to Cost Centre");
        addExpenseItemButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseItemButtonActionPerformed(evt);
            }
        });

        addExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addExpenseButton.setText("Add an Expense");
        addExpenseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        addCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addCostCentreButton.setText("Add a Cost Centre");
        addCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostCentreButtonActionPerformed(evt);
            }
        });

        editCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editCostCentreButton.setText("Edit an Existing Cost Centre");
        editCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCostCentreButtonActionPerformed(evt);
            }
        });

        editExistingExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editExistingExpense.setText("Edit an Existing Expense");
        editExistingExpense.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editExistingExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExistingExpenseActionPerformed(evt);
            }
        });

        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-report-button.png"))); // NOI18N
        reportsButton.setText("Create Reports");
        reportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d.png"))); // NOI18N

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addExpenseItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCostCentreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editCostCentreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editExistingExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editExistingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));
        jPanel4.setPreferredSize(new java.awt.Dimension(787, 102));

        title.setFont(new java.awt.Font("Lao UI", 1, 55)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cost Tracker Pro");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        returnHomeScreen.setStatus("Ready!");
        this.setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        returnHomeScreen.setStatus("Ready!");
        this.setVisible(false);

    }//GEN-LAST:event_homeButtonActionPerformed

    private void addExpenseItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseItemButtonActionPerformed
        AddExpenseToCC logExpense = new AddExpenseToCC();
        this.setVisible(false);
        logExpense.setVisible(true);
    }//GEN-LAST:event_addExpenseItemButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        AddExpense addExpense = new AddExpense();
        this.setVisible(false);
        addExpense.setVisible(true);
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void addCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostCentreButtonActionPerformed
        AddCostCentre addCostCentre = new AddCostCentre();
        this.setVisible(false);
        addCostCentre.setVisible(true);
    }//GEN-LAST:event_addCostCentreButtonActionPerformed

    private void editCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCostCentreButtonActionPerformed
        EditDeleteCostCentre editCostCentre = new EditDeleteCostCentre();
        this.setVisible(false);
        editCostCentre.setVisible(true);
    }//GEN-LAST:event_editCostCentreButtonActionPerformed

    private void editExistingExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExistingExpenseActionPerformed
    }//GEN-LAST:event_editExistingExpenseActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        ReportsPage createReport = new ReportsPage();
        this.setVisible(false);
        createReport.setVisible(true);
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void daySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daySelectActionPerformed

    private void expenseIDfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseIDfindActionPerformed
        findExpense();
    }//GEN-LAST:event_expenseIDfindActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearResults();
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (expenseResult != null) {
            expenseResult.deleteExpenseItem(expenseResult.getExpenseID());
            expenseResult.deleteExpense();
            clearResults();
            setStatus("Expense successfully deleted! - Ready");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (expenseResult != null) {
            expenseResult.setPayee(payeeInput.getText());
            expenseResult.setDescription(payeeInput.getText());

            int day = new Integer(daySelect.getSelectedItem().toString());
            int month = new Integer(monthSelect.getSelectedIndex());
            int year = new Integer(yearSelect.getSelectedItem().toString());
            GregorianCalendar date = new GregorianCalendar(year, month, day);

            expenseResult.setDate(date);
            this.findExpense();
            setStatus("Expense successfully updated! - Ready");


        }
    }//GEN-LAST:event_updateActionPerformed

    private void statusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDeleteExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDeleteExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDeleteExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDeleteExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EditDeleteExpense().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCostCentreButton;
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton addExpenseItemButton;
    private javax.swing.JTextField amountInput;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox daySelect;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea descInput;
    private javax.swing.JButton editCostCentreButton;
    private javax.swing.JButton editExistingExpense;
    private javax.swing.JLabel expenseID;
    private javax.swing.JButton expenseIDfind;
    private javax.swing.JTextField expenseIDinput;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox monthSelect;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JTextField payeeInput;
    private javax.swing.JButton reportsButton;
    private javax.swing.JTextField statusText;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JComboBox yearSelect;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the returnHomeScreen
     */
    public Home getReturnHomeScreen() {
        return returnHomeScreen;
    }

    /**
     * @param returnHomeScreen the returnHomeScreen to set
     */
    public void setReturnHomeScreen(Home returnHomeScreen) {
        this.returnHomeScreen = returnHomeScreen;
    }

    public void clearResults() {
        expenseID.setText("");
        payeeInput.setText("");
        descInput.setText("");
        amountInput.setText("");
        daySelect.setSelectedIndex(0);
        monthSelect.setSelectedIndex(0);
        yearSelect.setSelectedIndex(0);
        setStatus("Ready!");
    }

    public void findExpense() {
        try {
            if (!"".equals(expenseIDinput.getText())) {
                expenseResult = Expense.getExpenseByID(new Long(expenseIDinput.getText()));
                if (expenseResult != null) {
                    expenseID.setText("" + expenseResult.getExpenseID());
                    payeeInput.setText(expenseResult.getPayee());
                    descInput.setText(expenseResult.getDescription());
                    amountInput.setText("$" + expenseResult.getTotalAmount());
                    daySelect.setSelectedIndex(expenseResult.getDate().get(Calendar.DAY_OF_MONTH));
                    monthSelect.setSelectedIndex(expenseResult.getDate().get(Calendar.MONTH) + 1);
                    yearSelect.setSelectedIndex(expenseResult.getDate().get(Calendar.YEAR) - 104);
                    setStatus("Expense " + expenseID.getText() + " found! - You can now edit or delete it!");
                } else {
                    setStatus("Cannot find expense with this ID - try again!");
                    payeeInput.setText("");
                    descInput.setText("");
                    amountInput.setText("$");
                    daySelect.setSelectedIndex(0);
                    monthSelect.setSelectedIndex(0);
                    yearSelect.setSelectedIndex(0);
                }
            }
            else {
                setStatus("Please enter an ID to search for");
            }
        } catch (java.lang.NumberFormatException nfe) {
            clearResults();
            setStatus("Invalid Expense ID - Search again");
        }
    }

    public void setStatus(String s) {
        statusText.setText(s);
    }
}
