/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomeScreen.java
 *
 * Created on 23/05/2012, 4:27:28 PM
 */
package groupass;

import java.util.Calendar;
import java.util.List;

/**
 *
 * @author z3375080
 */
public class ReportsPage extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public ReportsPage() {
        initComponents();
    }
    private Home returnHomeScreen;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        activeCCbutton = new javax.swing.JButton();
        exceededCCbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        findButton = new javax.swing.JButton();
        costcentreIDinput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportOutput = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        statusText = new javax.swing.JTextField();
        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        addExpenseItemButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();
        addCostCentreButton = new javax.swing.JButton();
        editCostCentreButton = new javax.swing.JButton();
        editExistingExpense = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REPORTS", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N

        activeCCbutton.setText("Generate report of Active Cost Centres");
        activeCCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeCCbuttonActionPerformed(evt);
            }
        });

        exceededCCbutton.setText("View Cost Centres with Exceeded Limits");
        exceededCCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exceededCCbuttonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View expenses given a Cost Centre ID");

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-search-database.png"))); // NOI18N
        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(costcentreIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(findButton))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(costcentreIDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(findButton))))
        );

        reportOutput.setColumns(20);
        reportOutput.setEditable(false);
        reportOutput.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        reportOutput.setRows(5);
        jScrollPane1.setViewportView(reportOutput);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-action-back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        statusText.setEditable(false);
        statusText.setText("Ready!");
        statusText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(activeCCbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exceededCCbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123))
                            .addComponent(statusText, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(exceededCCbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(activeCCbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navigationPanel.setBackground(new java.awt.Color(244, 244, 244));
        navigationPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navigationPanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        navigationPanel.setPreferredSize(new java.awt.Dimension(266, 591));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-home.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        addExpenseItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-log.png"))); // NOI18N
        addExpenseItemButton.setText("Log an Expense to Cost Centre");
        addExpenseItemButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseItemButtonActionPerformed(evt);
            }
        });

        addExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addExpenseButton.setText("Add an Expense");
        addExpenseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        addCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-add-button.png"))); // NOI18N
        addCostCentreButton.setText("Add a Cost Centre");
        addCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCostCentreButtonActionPerformed(evt);
            }
        });

        editCostCentreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editCostCentreButton.setText("Edit an Existing Cost Centre");
        editCostCentreButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editCostCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCostCentreButtonActionPerformed(evt);
            }
        });

        editExistingExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-edit-button.png"))); // NOI18N
        editExistingExpense.setText("Edit an Existing Expense");
        editExistingExpense.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editExistingExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExistingExpenseActionPerformed(evt);
            }
        });

        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-report-button.png"))); // NOI18N
        reportsButton.setText("Create Reports");
        reportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f.png"))); // NOI18N

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reportsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editExistingExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editCostCentreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCostCentreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addExpenseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addExpenseItemButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCostCentreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editExistingExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));
        jPanel5.setPreferredSize(new java.awt.Dimension(787, 102));

        title.setFont(new java.awt.Font("Lao UI", 1, 55)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cost Tracker Pro");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        returnHomeScreen.setStatus("Ready!");
        this.setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        if (returnHomeScreen == null) {
            returnHomeScreen = new Home();
        }
        returnHomeScreen.setVisible(true);
        returnHomeScreen.setStatus("Ready!");
        this.setVisible(false);

    }//GEN-LAST:event_homeButtonActionPerformed

    private void addExpenseItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseItemButtonActionPerformed
        AddExpenseToCC logExpense = new AddExpenseToCC();
        logExpense.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addExpenseItemButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        AddExpense addExpense = new AddExpense();
        addExpense.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void addCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCostCentreButtonActionPerformed
        AddCostCentre addCostCentre = new AddCostCentre();
        addCostCentre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addCostCentreButtonActionPerformed

    private void editCostCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCostCentreButtonActionPerformed
        EditDeleteCostCentre editCostCentre = new EditDeleteCostCentre();
        editCostCentre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editCostCentreButtonActionPerformed

    private void editExistingExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExistingExpenseActionPerformed
        EditDeleteExpense editExpense = new EditDeleteExpense();
        editExpense.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editExistingExpenseActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void exceededCCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exceededCCbuttonActionPerformed
        reportOutput.setText("");
        List<CostCentre> costCentresExceedingLimit = CostCentre.getCostCentresExceedingLimit();
        StringBuilder sb = new StringBuilder();
        sb.append("------------ COST CENTRES EXCEEDING LIMIT -------------" + "\n");
        if (costCentresExceedingLimit != null) {
            System.out.println(costCentresExceedingLimit.toString());
            for (int i = 0; i < costCentresExceedingLimit.size(); i++) {
                String active;
                if (costCentresExceedingLimit.get(i).isActive()) {
                    active = "Active";
                } else {
                    active = "Inactive";
                }
                sb.append(costCentresExceedingLimit.get(i).getCostCentreId()).append(" - ").append(costCentresExceedingLimit.get(i).getName()).append(" - $").append(costCentresExceedingLimit.get(i).getAvailableFunds()).append(" - $").append(costCentresExceedingLimit.get(i).getTotalExpenses(costCentresExceedingLimit.get(i).getCostCentreId())).append(" - ").append(active).append("\n");

            }
            reportOutput.setText(sb.toString());
        } else {
            reportOutput.setText("No Cost Centres exceeding limit");
            setStatus("No Cost Centres exceeding limit");
        }
    }//GEN-LAST:event_exceededCCbuttonActionPerformed

    private void activeCCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeCCbuttonActionPerformed
        reportOutput.setText("");
        List<CostCentre> activeCostCentres = CostCentre.getActiveCostCentres();
        StringBuilder sb = new StringBuilder();
        sb.append("------------ ACTIVE COST CENTRES --------------" + "\n");
        if (activeCostCentres != null) {
            System.out.println(activeCostCentres.toString());
            for (int i = 0; i < activeCostCentres.size(); i++) {
                String hard = "Soft";
                if (activeCostCentres.get(i).isHardLimit())
                    hard = "Hard";
                sb.append(activeCostCentres.get(i).getCostCentreId()).append(" - ").append(activeCostCentres.get(i).getName()).append(" - $").append(activeCostCentres.get(i).getAvailableFunds()).append(" - $").append(activeCostCentres.get(i).getTotalExpenses(activeCostCentres.get(i).getCostCentreId())).append(" - " + hard + "\n");
                    
            }
            reportOutput.setText(sb.toString());
        } else {
            reportOutput.setText("No Cost Centres active");
            setStatus("No Cost Centres active");
        }
    }//GEN-LAST:event_activeCCbuttonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        reportOutput.setText("");
        try {
            CostCentre searchCostCentre = CostCentre.getCostCentreByID(new Integer(costcentreIDinput.getText()));
            if (searchCostCentre == null) {
                reportOutput.setText("No Cost Centres found with the ID: " + costcentreIDinput.getText());
                setStatus("No Cost Centres found with the ID: " + costcentreIDinput.getText());
            } else {
                List<Expense> searchExpenses = searchCostCentre.getExpenses();
                StringBuilder sb = new StringBuilder();
                sb.append("------ EXPENSES FOR COST CENTRE: ").append(costcentreIDinput.getText()).append(" ------" + "\n");
                if (searchExpenses != null) {
                    System.out.println(searchExpenses.toString());
                    for (int i = 0; i < searchExpenses.size(); i++) {
                        sb.append(searchExpenses.get(i).getExpenseID()).append(" - ").append(searchExpenses.get(i).getPayee()).append(" - ").append(searchExpenses.get(i).getDate().get(Calendar.DAY_OF_MONTH)).append("-").append(searchExpenses.get(i).getDate().get(Calendar.MONTH) + 1).append("-").append(searchExpenses.get(i).getDate().get(Calendar.YEAR));
                        sb.append(" - ").append(searchExpenses.get(i).getTotalAmount());
                        sb.append("\n");
                    }
                }
                reportOutput.setText(sb.toString());
            }
        } catch (java.lang.NumberFormatException nfe) {
            setStatus("Error - Check search string");
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void statusTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReportsPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activeCCbutton;
    private javax.swing.JButton addCostCentreButton;
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton addExpenseItemButton;
    private javax.swing.JButton back;
    private javax.swing.JTextField costcentreIDinput;
    private javax.swing.JButton editCostCentreButton;
    private javax.swing.JButton editExistingExpense;
    private javax.swing.JButton exceededCCbutton;
    private javax.swing.JButton findButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JTextArea reportOutput;
    private javax.swing.JButton reportsButton;
    private javax.swing.JTextField statusText;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the returnHomeScreen
     */
    public Home getReturnHomeScreen() {
        return returnHomeScreen;
    }

    /**
     * @param returnHomeScreen the returnHomeScreen to set
     */
    public void setReturnHomeScreen(Home returnHomeScreen) {
        this.returnHomeScreen = returnHomeScreen;
    }

    public void setStatus(String s) {
        statusText.setText(s);
    }
}
